apiVersion: v1
kind: ConfigMap
metadata:
  name: formflowapi-config
  namespace: formflow
data:
  APACHE_DOCUMENT_ROOT: /var/www/html/public
  DB_HOST: mysqlserverdb-service.formflow.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: formflow
  DB_USERNAME: root

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: formflow
type: Opaque
data:
  mysql-password: cm9vdA==  # base64 encoded value of 'root'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: formflowapi
  namespace: formflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formflowapi
  template:
    metadata:
      labels:
        app: formflowapi
    spec:
      initContainers:
      - name: init-migrate
        image: todorovamonika/formflow-backend:latest
        command: ["/bin/sh", "-c", "php artisan migrate --force"]
        env:
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: formflowapi-config
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: formflowapi-config
              key: DB_USERNAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: formflowapi-config
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
      containers:
      - name: formflowapi-container
        image: todorovamonika/formflow-backend:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: formflowapi-config
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: formflowapi-config
              key: DB_USERNAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: formflowapi-config
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
